### Get all bikes
GET http://localhost:3000/motos

### Get bike by ID
GET http://localhost:3000/motos/a5f2b3c7d9e8f1a

### Get all bike by brand
GET http://localhost:3000/motos?marca=honda

### Añadir una moto
POST http://localhost:3000/motos
Content-Type: application/json

{
    "name": "Ténéré 700",
    "year": 2023,
    "brand": "Yamaha",
    "image": "https://example.com/images/yamaha_tenere_700.jpg",
    "engine_capacity": 689
}

### Actualizar una moto
PATCH http://localhost:3000/motos/b3f5c8a3d7f9e01
Content-Type: application/json

{
    "year": 2023
}